### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by tajemouti** [tajemouti/rails_group_project#15]
## Hi Reviewer 👋 ##

This issue is created to provide task assignments and team information for [Rails group project](https://github.com/users/tajemouti/projects/1/views/1).

We have a team of 3 working on this project:

Team member #1: [Tajemouti](https://github.com/tajemouti)
Team member #2: [Ngala](https://github.com/ngalamac)
Team member #3: [Newton](https://github.com/mohammadnewton)

**Comment by ghost** [comment]
Hi Team, 

You can go ahead with your project
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/da75JuW2HHuBNqOHHE/giphy.gif"/>

## Highlights

✅ All tasks are created correctly and assigned fairly
✅ Tasks are descriptive 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
